"""Add dice rolls and initiative tracking models

Revision ID: 55ae7b5ff5e6
Revises: 92955475cea8
Create Date: 2026-02-06 14:43:05.309076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55ae7b5ff5e6'
down_revision = '92955475cea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dice_rolls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dice_expression', sa.String(length=100), nullable=False),
    sa.Column('result', sa.Integer(), nullable=False),
    sa.Column('individual_rolls', sa.JSON(), nullable=False),
    sa.Column('modifier', sa.Integer(), nullable=True),
    sa.Column('has_advantage', sa.Boolean(), nullable=True),
    sa.Column('has_disadvantage', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['game_tables.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('initiative_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('current_turn', sa.Integer(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['game_tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('initiative_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=100), nullable=False),
    sa.Column('initiative_score', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('custom_field', sa.String(length=100), nullable=True),
    sa.Column('is_npc', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['initiative_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=True),
    sa.Column('can_edit', sa.Boolean(), nullable=True),
    sa.Column('granted_by', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('note_id', 'user_id', name='unique_note_user_permission')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_template', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('original_note_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_note_original', 'notes', ['original_note_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_note_original', type_='foreignkey')
        batch_op.drop_column('original_note_id')
        batch_op.drop_column('is_template')
        batch_op.drop_column('description')

    op.drop_table('note_permissions')
    op.drop_table('initiative_entries')
    op.drop_table('initiative_sessions')
    op.drop_table('dice_rolls')
    # ### end Alembic commands ###
